#!/usr/bin/env bash
set -euo pipefail

mkdir -p docs/src/generated

cat > docs/src/generated/tools.md <<'EOF'
# Tooling Snapshot

This page is generated by `scripts/generate-docs.sh` before `mdbook build`.

- terraform-docs: required in docs workflow
- helm-docs: required in docs workflow
EOF
